# Workflow name.
name: Courier Pipeline

# Build triggers.
on:
    push:
    pull_request:

# Jobs to do.
jobs:
    Courier_Pipeline:

        # Run target.
        runs-on: ubuntu-latest
    
        # Job steps.
        steps:

            # Step 1. Checkout Repo.
            - name: Checkout Repo
              uses: actions/checkout@v3
            
            # Step 2. Install dependencies.
            - name: Install Dependencies
              run: |
                echo "Installing dependencies..."
                sudo apt-get update
                sudo apt-get install -y make
            
            # Step 3. Build CPP project test bench.
            - name: Build
              run: |
                echo -e "\n[+] Building courier...\n"
                make test
            
            # Step 4. Run test bench
            - name: Test
              run: |
                echo -e "\n[+] Running test bench...\n"
                ./bins/test_main
            
            # Step 5. Run valgrind
            - name: Valgrind
              run: |
                echo -e "\n[+] Running valgrind...\n"
                valgrind --leak-check=full ./bins/test_main
